import 'package:flutter/material.dart';
import '../../core/services/mitra_repository.dart';
import '../../core/services/auth_service.dart';
import '../../core/models/mitra_model.dart';

class RegisterViewModel with ChangeNotifier {
  final MitraRepository _mitraRepository = MitraRepository();
  final AuthService _authService = AuthService();
  
  bool _isLoading = false;
  bool _isRegistered = false;
  bool _isPasswordVisible = false;
  String? _errorMessage;

  bool get isLoading => _isLoading;
  bool get isRegistered => _isRegistered;
  bool get isPasswordVisible => _isPasswordVisible;
  String? get errorMessage => _errorMessage;

  void togglePasswordVisibility() {
    _isPasswordVisible = !_isPasswordVisible;
    notifyListeners();
  }

  Future<void> register(String username, String email, String password, String phoneNumber) async {
    // Validate all fields are filled
    if (username.isEmpty || email.isEmpty || password.isEmpty || phoneNumber.isEmpty) {
      _errorMessage = 'Semua field harus diisi';
      notifyListeners();
      return;
    }
    
    // Validate password length
    if (password.length < 8) {
      _errorMessage = 'Password minimal 8 karakter';
      notifyListeners();
      return;
    }
    
    // Validate email format
    final emailRegex = RegExp(r'^[\w-\.]+@([\w-]+\.)+[\w-]{2,4}$');
    if (!emailRegex.hasMatch(email)) {
      _errorMessage = 'Format email tidak valid';
      notifyListeners();
      return;
    }

    _isLoading = true;
    _errorMessage = null;
    notifyListeners();

    try {
      debugPrint('Starting registration for email: $email');
      
      // Create a new MitraModel with the registration data
      // The ID will be generated by the backend
      final newMitra = MitraModel(
        idMitra: '', // Will be generated by backend
        namaMitra: username,
        emailMitra: email,
        passwordMitra: password,
        noTelpMitra: phoneNumber,
      );

      debugPrint('Calling API to create mitra...');
      // Call the API to create the mitra in the database
      final createdMitra = await _mitraRepository.createMitra(newMitra);
      
      debugPrint('Mitra created successfully with ID: ${createdMitra.idMitra}');
      
      // Save the user session after successful registration
      await _authService.saveMitraSession(createdMitra);
      
      debugPrint('Session saved successfully');
      _isRegistered = true;
    } catch (e) {
      debugPrint('Registration error: $e');
      // Parse error message for better user feedback
      final errorStr = e.toString();
      
      if (errorStr.contains('email') && errorStr.contains('already been taken')) {
        _errorMessage = 'Email sudah terdaftar. Gunakan email lain.';
      } else if (errorStr.contains('password') && errorStr.contains('at least 8 characters')) {
        _errorMessage = 'Password minimal 8 karakter.';
      } else if (errorStr.contains('Validation failed')) {
        _errorMessage = 'Validasi gagal. Periksa kembali data Anda.';
      } else if (errorStr.contains('No internet connection')) {
        _errorMessage = 'Tidak ada koneksi internet.';
      } else {
        _errorMessage = 'Gagal mendaftar. ${errorStr.replaceAll('Exception: Failed to create mitra: ', '')}';
      }
    } finally {
      _isLoading = false;
      notifyListeners();
    }
  }
}