import 'package:flutter/foundation.dart';
import '../models/mitra_model.dart';
import '../models/bumdes_model.dart';
import '../services/mitra_repository.dart';
import '../services/bumdes_repository.dart';

/// Example ViewModel showing how to handle authentication with backend
/// 
/// Usage in Login Screen:
/// ```dart
/// final authViewModel = AuthViewModelExample();
/// 
/// // Login as Mitra
/// bool success = await authViewModel.loginAsMitra(email, password);
/// 
/// // Login as Bumdes
/// bool success = await authViewModel.loginAsBumdes(email, password);
/// ```
class AuthViewModelExample extends ChangeNotifier {
  final MitraRepository _mitraRepository = MitraRepository();
  final BumdesRepository _bumdesRepository = BumdesRepository();
  
  MitraModel? _currentMitra;
  BumdesModel? _currentBumdes;
  bool _isLoading = false;
  String? _errorMessage;
  
  // Getters
  MitraModel? get currentMitra => _currentMitra;
  BumdesModel? get currentBumdes => _currentBumdes;
  bool get isLoading => _isLoading;
  String? get errorMessage => _errorMessage;
  bool get isLoggedInAsMitra => _currentMitra != null;
  bool get isLoggedInAsBumdes => _currentBumdes != null;
  
  /// Login as Mitra
  Future<bool> loginAsMitra(String email, String password) async {
    _isLoading = true;
    _errorMessage = null;
    notifyListeners();
    
    try {
      _currentMitra = await _mitraRepository.loginMitra(email, password);
      _isLoading = false;
      
      if (_currentMitra != null) {
        notifyListeners();
        return true;
      } else {
        _errorMessage = 'Invalid email or password';
        notifyListeners();
        return false;
      }
    } catch (e) {
      _errorMessage = e.toString();
      _isLoading = false;
      notifyListeners();
      if (kDebugMode) {
        print('Error during Mitra login: $e');
      }
      return false;
    }
  }
  
  /// Login as Bumdes
  Future<bool> loginAsBumdes(String email, String password) async {
    _isLoading = true;
    _errorMessage = null;
    notifyListeners();
    
    try {
      _currentBumdes = await _bumdesRepository.loginBumdes(email, password);
      _isLoading = false;
      
      if (_currentBumdes != null) {
        notifyListeners();
        return true;
      } else {
        _errorMessage = 'Invalid email or password';
        notifyListeners();
        return false;
      }
    } catch (e) {
      _errorMessage = e.toString();
      _isLoading = false;
      notifyListeners();
      if (kDebugMode) {
        print('Error during Bumdes login: $e');
      }
      return false;
    }
  }
  
  /// Register new Mitra
  Future<bool> registerMitra({
    required String name,
    required String phone,
    required String email,
    required String password,
  }) async {
    _isLoading = true;
    _errorMessage = null;
    notifyListeners();
    
    try {
      final newMitra = MitraModel(
        idMitra: '', // Will be generated by backend
        namaMitra: name,
        noTelpMitra: phone,
        emailMitra: email,
        passwordMitra: password,
      );
      
      _currentMitra = await _mitraRepository.createMitra(newMitra);
      _isLoading = false;
      notifyListeners();
      return true;
    } catch (e) {
      _errorMessage = e.toString();
      _isLoading = false;
      notifyListeners();
      if (kDebugMode) {
        print('Error during Mitra registration: $e');
      }
      return false;
    }
  }
  
  /// Register new Bumdes
  Future<bool> registerBumdes({
    required String name,
    required String phone,
    required String email,
    required String password,
  }) async {
    _isLoading = true;
    _errorMessage = null;
    notifyListeners();
    
    try {
      final newBumdes = BumdesModel(
        idBumdes: '', // Will be generated by backend
        namaBumdes: name,
        noTelpBumdes: phone,
        emailBumdes: email,
        passwordBumdes: password,
      );
      
      _currentBumdes = await _bumdesRepository.createBumdes(newBumdes);
      _isLoading = false;
      notifyListeners();
      return true;
    } catch (e) {
      _errorMessage = e.toString();
      _isLoading = false;
      notifyListeners();
      if (kDebugMode) {
        print('Error during Bumdes registration: $e');
      }
      return false;
    }
  }
  
  /// Logout
  void logout() {
    _currentMitra = null;
    _currentBumdes = null;
    _errorMessage = null;
    notifyListeners();
  }
  
  /// Update Mitra profile
  Future<bool> updateMitraProfile({
    required String name,
    required String phone,
    required String email,
  }) async {
    if (_currentMitra == null) return false;
    
    _isLoading = true;
    notifyListeners();
    
    try {
      final updatedMitra = MitraModel(
        idMitra: _currentMitra!.idMitra,
        namaMitra: name,
        noTelpMitra: phone,
        emailMitra: email,
        passwordMitra: _currentMitra!.passwordMitra,
      );
      
      _currentMitra = await _mitraRepository.updateMitra(
        _currentMitra!.idMitra,
        updatedMitra,
      );
      
      _isLoading = false;
      notifyListeners();
      return true;
    } catch (e) {
      _errorMessage = e.toString();
      _isLoading = false;
      notifyListeners();
      return false;
    }
  }
}
