import 'package:flutter/foundation.dart';
import '../models/pangan_model.dart';
import '../services/pangan_repository.dart';

/// Example ViewModel showing how to integrate with backend API
/// 
/// Usage:
/// 1. Create instance: final viewModel = CatalogViewModelWithApi();
/// 2. Load products: await viewModel.loadProducts();
/// 3. Listen to changes: Provider.of<CatalogViewModelWithApi>(context)
class CatalogViewModelWithApi extends ChangeNotifier {
  final PanganRepository _panganRepository = PanganRepository();
  
  List<PanganModel> _products = [];
  bool _isLoading = false;
  String? _errorMessage;
  
  // Getters
  List<PanganModel> get products => _products;
  bool get isLoading => _isLoading;
  String? get errorMessage => _errorMessage;
  
  /// Load all products from backend
  Future<void> loadProducts() async {
    _isLoading = true;
    _errorMessage = null;
    notifyListeners();
    
    try {
      _products = await _panganRepository.getAllPangan();
      _isLoading = false;
      notifyListeners();
    } catch (e) {
      _errorMessage = e.toString();
      _isLoading = false;
      notifyListeners();
      if (kDebugMode) {
        print('Error loading products: $e');
      }
    }
  }
  
  /// Search products by name
  Future<void> searchProducts(String query) async {
    if (query.isEmpty) {
      await loadProducts();
      return;
    }
    
    _isLoading = true;
    notifyListeners();
    
    try {
      _products = await _panganRepository.searchPangan(query);
      _isLoading = false;
      notifyListeners();
    } catch (e) {
      _errorMessage = e.toString();
      _isLoading = false;
      notifyListeners();
    }
  }
  
  /// Filter products by price range
  Future<void> filterByPrice(double minPrice, double maxPrice) async {
    _isLoading = true;
    notifyListeners();
    
    try {
      _products = await _panganRepository.getPanganByPriceRange(minPrice, maxPrice);
      _isLoading = false;
      notifyListeners();
    } catch (e) {
      _errorMessage = e.toString();
      _isLoading = false;
      notifyListeners();
    }
  }
  
  /// Get product by ID
  Future<PanganModel?> getProductById(String id) async {
    try {
      return await _panganRepository.getPanganById(id);
    } catch (e) {
      if (kDebugMode) {
        print('Error getting product: $e');
      }
      return null;
    }
  }
  
  /// Create new product (Admin feature)
  Future<bool> createProduct({
    required String name,
    required String description,
    required double price,
    required String photoId,
  }) async {
    try {
      final newPangan = PanganModel(
        idPangan: '', // Will be generated by backend
        namaPangan: name,
        deskripsiPangan: description,
        hargaPangan: price,
        idFotoPangan: photoId,
      );
      
      await _panganRepository.createPangan(newPangan);
      
      // Reload products to get updated list
      await loadProducts();
      
      return true;
    } catch (e) {
      _errorMessage = e.toString();
      notifyListeners();
      if (kDebugMode) {
        print('Error creating product: $e');
      }
      return false;
    }
  }
  
  /// Update existing product (Admin feature)
  Future<bool> updateProduct({
    required String id,
    required String name,
    required String description,
    required double price,
    required String photoId,
  }) async {
    try {
      final updatedPangan = PanganModel(
        idPangan: id,
        namaPangan: name,
        deskripsiPangan: description,
        hargaPangan: price,
        idFotoPangan: photoId,
      );
      
      await _panganRepository.updatePangan(id, updatedPangan);
      
      // Reload products to get updated list
      await loadProducts();
      
      return true;
    } catch (e) {
      _errorMessage = e.toString();
      notifyListeners();
      if (kDebugMode) {
        print('Error updating product: $e');
      }
      return false;
    }
  }
  
  /// Delete product (Admin feature)
  Future<bool> deleteProduct(String id) async {
    try {
      await _panganRepository.deletePangan(id);
      
      // Remove from local list
      _products.removeWhere((product) => product.idPangan == id);
      notifyListeners();
      
      return true;
    } catch (e) {
      _errorMessage = e.toString();
      notifyListeners();
      if (kDebugMode) {
        print('Error deleting product: $e');
      }
      return false;
    }
  }
}
